
package com.example.demo;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISoapWebService", targetNamespace = "http://demo.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ISoapWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.example.com/ISoapWebService/getEmployeeRequest", output = "http://demo.example.com/ISoapWebService/getEmployeeResponse")
    public String getEmployee();

}
