
package com.example.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapControllerService", targetNamespace = "http://demo.example.com/", wsdlLocation = "http://localhost:8080/ISoapWebService/employee?wsdl")
public class SoapControllerService
    extends Service
{

    private final static URL SOAPCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPCONTROLLERSERVICE_EXCEPTION;
    private final static QName SOAPCONTROLLERSERVICE_QNAME = new QName("http://demo.example.com/", "SoapControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ISoapWebService/employee?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPCONTROLLERSERVICE_WSDL_LOCATION = url;
        SOAPCONTROLLERSERVICE_EXCEPTION = e;
    }

    public SoapControllerService() {
        super(__getWsdlLocation(), SOAPCONTROLLERSERVICE_QNAME);
    }

    public SoapControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPCONTROLLERSERVICE_QNAME, features);
    }

    public SoapControllerService(URL wsdlLocation) {
        super(wsdlLocation, SOAPCONTROLLERSERVICE_QNAME);
    }

    public SoapControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPCONTROLLERSERVICE_QNAME, features);
    }

    public SoapControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISoapWebService
     */
    @WebEndpoint(name = "SoapControllerPort")
    public ISoapWebService getSoapControllerPort() {
        return super.getPort(new QName("http://demo.example.com/", "SoapControllerPort"), ISoapWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoapWebService
     */
    @WebEndpoint(name = "SoapControllerPort")
    public ISoapWebService getSoapControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://demo.example.com/", "SoapControllerPort"), ISoapWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPCONTROLLERSERVICE_EXCEPTION!= null) {
            throw SOAPCONTROLLERSERVICE_EXCEPTION;
        }
        return SOAPCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
